### ISSUE TITLE
Wrong dates

### ISSUE THREAD

**Issue by JoeOD** [jsta/wayback#1]
Hello, thanks for this great package,

I find that the package often returns data from dates other than those I specify. For example:

wsj2018 <- wayback_url(url = "https://www.wsj.com", timestamp = "20180208")
wsj2018pclass <- wayback_scrape(wsj2018$url, "div p")

For me, this returns data from February 7th, not 8th, as specified. 

Is this a known issue?

**Comment by jsta** [comment]
I've not heard of this issue. My guess is that time-zones are either not being translated or are being mis-translated. Can you tell what time zone you have as the default for your machine? 

In any case, I am unlikely to look into this issue myself (PRs are welcome). My recommendation is to use the `wayback` package at: https://github.com/hrbrmstr/wayback

**Comment by JoeOD** [comment]
Sys.timezone() returns [1] "America/Phoenix" and Sys.time says i'm on
mountain standard time. I took a look at the examples of how to use
https://github.com/hrbrmstr/wayback and I'm not quite sure what it does.
Will it do scraping of the kind your package does? I'm looking to scrape
text, e.g., news headlines and articles.

**Comment by jsta** [comment]
I believe that `read_memento` in `hrbrmstr/wayback` will do scaping.
